[v1]
"cargo-edit 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-add", "cargo-rm", "cargo-upgrade"]
"cargo-web 0.6.26 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-web"]
"clippy 0.0.154 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-clippy"]
"sonic-pi-tool 0.1.0 (git+https://github.com/lpil/sonic-pi-tool/#9edf4e38ea7e94f110cfe9acdd3cbd9fd4728e89)" = ["sonic-pi-tool"]
"wasm-bindgen-cli 0.2.11 (registry+https://github.com/rust-lang/crates.io-index)" = ["wasm-bindgen", "wasm2es6js"]
"wasm-gc 0.1.1 (git+https://github.com/alexcrichton/wasm-gc#e406f9ce26d8c88dd63ff2d6106f2e48f95626a0)" = ["wasm-gc"]
"wasm-pack 0.8.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["wasm-pack"]
