" Things to do:
" Set up NERDTree config options
" Read through spf13 vim config and apply the useful stuff from it
" Set up alt-delete and alt-movements in insert mode the way you like them
" Add comments explaining everything
" set up vim-one colors: https://github.com/rakr/vim-one
" set up vim-one tmux snd tmuxline support
" read this:
" http://homeonrails.com/2016/05/truecolor-in-gnome-terminal-tmux-and-neovim/
" set up vim-airline: https://github.com/vim-airline/vim-airline

execute pathogen#infect()
" generate documentation for all pathogen-installed plugins
" Helptags

" this might be unnecessary, but it's nice to be clear
set nocompatible

syntax on
set encoding=utf-8

" turn on filetype, plugin, and indent
filetype plugin indent on

" set up the theme and syntax highlighting
set t_8b=[48;2;%lu;%lu;%lum
set t_8f=[38;2;%lu;%lu;%lum

let g:one_allow_italics = 1

colorscheme one
set background=dark

let g:airline_theme='one'

" reloads when a file is changed in the background
set autoread

" incremental search
set incsearch
" highlighted search
" set hlsearch

set backspace=indent,eol,start
set whichwrap+=<,>

set autoindent

set history=50

set ruler
set showcmd
set number

set backup
" set vim directories for undo, backup, and swap files
set undodir=$HOME/.vim/.undo//
set backupdir=$HOME/.vim/.backup//
set directory^=$HOME/.vim/.swp//

set scrolloff=3

" allow files to be open as buffers without being visible 
set hidden

" plugin settings and commands
let g:ctrlp_show_hidden = 1
let g:ctrlp_working_path_mode = 'a'

" NERDTree Settings
nnoremap <C-o> :NERDTreeToggle<CR>
let g:NERDTreeWinSize=18
let g:NERDTreeShowHidden=1
autocmd vimenter * NERDTree | wincmd l
autocmd tabnew * NERDTree | wincmd l
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" ack package settings
let g:ackprg = 'ag --vimgrep --smart-case'
cnoreabbrev ag Ack
cnoreabbrev aG Ack
cnoreabbrev Ag Ack
cnoreabbrev AG Ack

" ****** KEYBINDINGS ******
let mapleader = " "

" manually reload vim config
nnoremap <leader>r :source ~/.vim/vimrc<CR> 
nnoremap <leader>w :w<CR>
nnoremap <leader>q :q<CR>

" move between windows
noremap <leader>j <C-W>j
noremap <leader>k <C-W>k
noremap <leader>l <C-W>l
noremap <leader>h <C-W>h

" create tabs
noremap <leader>n :tabnew<CR>

" move between tabs
noremap <leader><Left> :tabp<CR>
noremap <leader><Right> :tabn<CR>

" scrolling
noremap <C-n> 6<C-e>6j
noremap <C-m> 6<C-y>6k

noremap <C-j> 6j
noremap <C-k> 6k

" start / end of line movement like emacs
noremap <C-a> ^
noremap <C-e> $

inoremap <C-a> <C-o>^
inoremap <C-e> <C-o>$

cnoremap <C-a> <Home>
cnoremap <C-e> <End>


" move lines of text around vertically
nnoremap <C-M-j> mz:m+<cr>`z
nnoremap <C-M-k> mz:m-2<cr>`z
vnoremap <C-M-j> :m'>+<cr>`<my`>mzgv`yo`z
vnoremap <C-M-k> :m'<-2<cr>`>my`<mzgv`yo`z

" moving around in insert mode
inoremap <M-j> <C-o>j
inoremap <M-k> <C-o>k
inoremap <M-b> <C-o>b
inoremap <M-e> <C-o>e

