" Things to do:
" Set up NERDTree config options
" Read through spf13 vim config and apply the useful stuff from it
" Set up alt-delete and alt-movements in insert mode the way you like them
" Add comments explaining everything
" set up vim-one colors: https://github.com/rakr/vim-one
" set up vim-one tmux snd tmuxline support
" read this:
" http://homeonrails.com/2016/05/truecolor-in-gnome-terminal-tmux-and-neovim/
" set up vim-airline: https://github.com/vim-airline/vim-airline
"

execute pathogen#infect()
" generate documentation for all pathogen-installed plugins
Helptags

" this might be unnecessary, but it's nice to be clear
set nocompatible

filetype plugin indent on
syntax on
set encoding=utf-8

colorscheme one
set background=dark

let g:airline_theme='one'

" reloads when a file is changed in the background
set autoread

" incremental search
set incsearch
" highlighted search
" set hlsearch

set backspace=indent,eol,start
set whichwrap+=<,>

set autoindent

set backup

set history=50

set ruler
set showcmd

set undodir=$HOME/.vim/.undo//
set backupdir=$HOME/.vim/.backup//
set directory^=$HOME/.vim/.swp//

set scrolloff=3

" allow files to be open as buffers without being visible 
set hidden

let mapleader = " "

" plugin settings and commands
let g:ctrlp_show_hidden = 1
let g:ctrlp_working_path_mode = 'a'

nnoremap <C-o> :NERDTreeToggle<CR>

nnoremap <silent> <C-C> :nohlsearch<CR>

let g:ackprg = 'ag --vimgrep --smart-case'
cnoreabbrev ag Ack
cnoreabbrev aG Ack
cnoreabbrev Ag Ack
cnoreabbrev AG Ack

" manually reload vim config
nnoremap <leader>r :source ~/.vim/vimrc<CR> 

" use backspace to delete in normal mode
nnoremap <BS> X

nnoremap <M-BS> db
inoremap <M-BS> <C-O><M-BS>

" move between windows
nnoremap <C-J> <C-W>j
nnoremap <C-K> <C-W>k
nnoremap <C-L> <C-W>l
nnoremap <C-H> <C-W>h

" move between tabs
nnoremap <C-M-Left> :tabp<CR>
nnoremap <C-M-Right> :tabn<CR>

" scrolling
nnoremap <C-N> 5<C-E>M
nnoremap <C-M> 5<C-Y>M

" start / end of line movement
noremap <C-A> ^
noremap <C-E> $

inoremap <C-A> <C-O>^
inoremap <C-E> <C-O>$

" move lines of text around vertically
nmap <M-j> mz:m+<cr>`z
nmap <M-k> mz:m-2<cr>`z
vmap <M-j> :m'>+<cr>`<my`>mzgv`yo`z
vmap <M-k> :m'<-2<cr>`>my`<mzgv`yo`z

if has("mac") || has("macunix")
	nmap <D-j> <M-j>
	nmap <D-k> <M-k>
	vmap <D-j> <M-j>
	vmap <D-k> <M-k>
endif

