#!/usr/bin/env python3

import sys
import os
import axi

def main():
    mode = sys.argv[1]
    filename = sys.argv[2]
    drawing = axi.Drawing.load(filename)
    drawing = drawing.sort_paths()
    drawing = drawing.join_paths(0.001)
    if mode == '--test':
        outfile = sys.argv[3]
        drawing.render().write_to_png('{}.png'.format(outfile))
    elif mode == '--draw':
        axi.draw(drawing)

if __name__ == '__main__':
    main()

